### ISSUE TITLE
Getting error while importing enums from tez.

### ISSUE THREAD

**Issue by VikasRathod314** [abhishekkrthakur/tez#47]
Traceback (most recent call last):
  File "/content/tez/tez/model/model.py", line 12, in <module>
    from tez import enums
  File "/content/tez/tez/model/tez.py", line 11, in <module>
    from tez import enums
ImportError: cannot import name 'enums' from 'tez' (/content/tez/tez/model/tez.py)

Waiting for positive reply.

**Comment by abhishekkrthakur** [comment]
How do you install tez? Could you please provide an example to reproduce the error?

**Comment by VikasRathod314** [comment]
Hello Abhishek sir, I install tez by using this command ---- pip inatall tez . as you said in video.

**Comment by abhishekkrthakur** [comment]
I'm not sure if i can reproduce. the video can be old. please checkout the latest examples here: https://github.com/abhishekkrthakur/tez/tree/main/examples
